version: '3'
services:
  mongo:
    image: 'mongo:latest'
    ports:
      - "27017:27017"
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MGDATABASE=mongo
      - MGPASSWORD=password
      - MGPORT=27017
    depends_on:
      - mongo
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app